# Useful for Nominal Categorical Data

In [89]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from pathlib import Path
from sklearn.model_selection import train_test_split

In [90]:
root_path = Path().cwd().parent.parent.parent
data_path = root_path / "Datasets" / "cars.csv"

In [91]:
df = pd.read_csv(data_path)

In [92]:
df.head()

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000


In [93]:
df = df.drop(columns = ['km_driven'])

In [94]:
df.shape

(8128, 4)

In [95]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [96]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [97]:
X_train

,brand,fuel
6518,Tata,Petrol
6144,Honda,Petrol
6381,Hyundai,Diesel
438,Maruti,Diesel
5939,Maruti,Petrol
...,...,...
5226,Mahindra,Diesel
5390,Maruti,Diesel
860,Hyundai,Petrol
7603,Maruti,Diesel


In [98]:
X_train['fuel'].nunique()

4

In [99]:
X_train['brand'].nunique()

32

In [100]:
ohe = OneHotEncoder()

In [101]:
ohe.fit_transform(X_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13004 stored elements and shape (6502, 36)>

Output of OHE -> Sparse Matrix

In [102]:
X_train = ohe.fit_transform(X_train).toarray()
X_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(6502, 36))

In [103]:
X_train.shape

(6502, 36)

so 32 from brand + 4 from fuel

In [104]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [105]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [106]:
# Useful Function
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

In [107]:
pd.DataFrame(X_train,columns=ohe.get_feature_names_out())

,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0


In [109]:
ohe.inverse_transform(np.array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.,1.,0.]).reshape(1,36))

array([['Audi', 'LPG']], dtype=object)

## Dummy Variable Trap in One-Hot Encoding (OHE)

### What it is
When you one-hot encode a categorical variable with **k** categories, you create **k** binary columns. But these k columns are **linearly dependent** — knowing any (k-1) of them tells you the value of the last one (if all others are 0, the last one must be 1).

This introduces **perfect multicollinearity** among the dummy columns — this is the **dummy variable trap**.

**Example:** `Color = [Red, Blue, Green]` → OHE gives 3 columns:
`Color_Red, Color_Blue, Color_Green`
If `Color_Red=0` and `Color_Blue=0`, then `Color_Green` **must be 1** — it's redundant information.

### Why it's a problem
- Causes **perfect multicollinearity** in the design matrix.
- For linear models, this makes `(XᵀX)` **non-invertible (singular)**, so coefficients become unstable, undefined, or wildly large — the model can't uniquely determine each dummy's individual effect.

### How to resolve it
**Drop one category (k-1 dummies instead of k)** — commonly called **dummy encoding**.
- The dropped category becomes the **reference/baseline** category.
- All other coefficients are interpreted *relative to* this baseline.
- In pandas: `pd.get_dummies(df, drop_first=True)`
- In sklearn: `OneHotEncoder(drop='first')`

---

### ⚠️ Important: This only matters for linear models

| Model Type | Affected by multicollinearity? |
|---|---|
| Linear/Logistic Regression | ✅ Yes — coefficients become unstable/uninterpretable |
| Tree-based models (Decision Trees, Random Forest, XGBoost, etc.) | ❌ No — unaffected |

**Why tree-based models are unaffected:**
Trees split on **one feature at a time** based on information gain/impurity reduction — they don't invert a matrix or estimate coefficients simultaneously across features. Redundant/correlated columns don't break the math; the tree simply picks whichever correlated feature gives the best split at each node. So `drop_first=True` is **not required** for tree-based models — you can safely use all k dummy columns.

In [110]:
# drop
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

ohe = OneHotEncoder(drop='first')
ohe.fit_transform(X_train).shape

(6502, 34)

In [111]:
ohe.drop_idx_

array([0, 0], dtype=object)

# Parameters in OHE

# Sparse Output = [False,True]

In [112]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [113]:
ohe = OneHotEncoder(sparse_output=False)
ohe.fit_transform(X_train)

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(6502, 36))

Output is a numpy array itself

# Handling Rare Categories

In [114]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [115]:
# handling rare categories
X_train['brand'].value_counts()

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Ambassador          3
MG                  3
Daewoo              3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [117]:
X_train['fuel'].value_counts()

fuel
Diesel    3545
Petrol    2880
CNG         46
LPG         31
Name: count, dtype: int64

In [118]:
# using min_frequency
ohe = OneHotEncoder(sparse_output=False, min_frequency=100)
ohe.fit_transform(X_train).shape

(6502, 14)

In [119]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_Diesel', 'fuel_Petrol', 'fuel_infrequent_sklearn'],
      dtype=object)

# handling Unknown Category

In [120]:
# how to handle unknown category
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

c:\Users\avanindra Bose\ML Tips\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


ValueError: Found unknown categories [np.str_('local')] in column 0 during transform

In [121]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

c:\Users\avanindra Bose\ML Tips\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

In [122]:
ohe.inverse_transform(np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]).reshape(1,36))

array([[None, 'Petrol']], dtype=object)

OneHotEncoder: `drop='first'` + `handle_unknown='ignore'`
When using:
```python
OneHotEncoder(
    drop='first',
    handle_unknown='ignore'
)
```
Suppose the training categories are:
```text
Delhi, Mumbai, Raipur
```
With `drop='first'`, the first category (`Delhi`) is dropped and becomes the reference category:
```text
Delhi  → [0, 0]
Mumbai → [1, 0]
Raipur → [0, 1]
```
> **The all-zero vector represents the dropped/reference category.**
Problem with an unknown category
If `Bangalore` appears during inference but was not present during training:
```text
Bangalore → [0, 0]
```
Now:
```text
Delhi      → [0, 0]
Bangalore  → [0, 0]
```
So the model cannot distinguish the unknown category from the dropped category.
Key takeaway
> With `drop='first'` and `handle_unknown='ignore'`, an unknown category can be represented by the same all-zero vector as the dropped/reference category.
This is not the model thinking about the dummy variable trap. `drop='first'` simply makes the first category the reference category.