In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [3]:
root_path = Path().cwd().parent.parent.parent
data_path = root_path / "Datasets" / "customers.csv"

In [4]:
df = pd.read_csv(data_path)

In [5]:
df.shape

(50, 5)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        50 non-null     int64
 1   gender     50 non-null     str  
 2   review     50 non-null     str  
 3   education  50 non-null     str  
 4   purchased  50 non-null     str  
dtypes: int64(1), str(4)
memory usage: 2.1 KB


In [7]:
df.head()

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No


# Ordinal Encoding is only Applied to those columns which has some kind of Order

In [8]:
cat_cols = df[['review','education']]

In [9]:
cat_cols['review'].unique()

<StringArray>
['Average', 'Poor', 'Good']
Length: 3, dtype: str

In [10]:
cat_cols['education'].unique()

<StringArray>
['School', 'UG', 'PG']
Length: 3, dtype: str

In [11]:
# specification of Order is Important Here !!
ode = OrdinalEncoder(categories=[['Poor','Average','Good'] , ['School','UG','PG']])
# It is mapped to increasing nuerical values

In [12]:
X_train,X_test = train_test_split(cat_cols,test_size=0.2,random_state=42)

In [13]:
X_train.shape

(40, 2)

In [14]:
X_test.shape

(10, 2)

In [15]:
X_train

,review,education
12,Poor,School
4,Average,UG
37,Average,PG
8,Average,UG
3,Good,PG
6,Good,School
41,Good,PG
46,Poor,PG
47,Good,PG
15,Poor,UG


In [16]:
X_test

,review,education
13,Average,School
39,Poor,PG
30,Average,UG
45,Poor,PG
17,Poor,UG
48,Good,UG
26,Poor,PG
25,Good,School
32,Average,UG
19,Poor,PG


In [17]:
X_train = ode.fit_transform(X_train)

In [18]:
X_test = ode.transform(X_test)

In [19]:
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

# Few Important Attributes of ODE

In [20]:
ode.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [21]:
ode.get_feature_names_out

<bound method OneToOneFeatureMixin.get_feature_names_out of OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])>

In [22]:
ode.n_features_in_

2

In [23]:
ode.inverse_transform(np.array([1,0]).reshape(1,2))

array([['Average', 'School']], dtype=object)

In [24]:
ode.transform(np.array(['Good','School']).reshape(1,2))

c:\Users\avanindra Bose\ML Tips\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2., 0.]])

# Parameters of Ordinal Encoding

# Handling Unknown Categories (Important for Production Pipelines)

In [25]:
ode.transform(np.array(['Good','Dsitinction']).reshape(1,2))

c:\Users\avanindra Bose\ML Tips\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


ValueError: Found unknown categories [np.str_('Dsitinction')] in column 1 during transform

__Unknown Categories will throw an error if not handled Explicitly__

In [26]:
# set unknown value
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],
                    handle_unknown='use_encoded_value',
                    unknown_value=-1)
X_train,X_test = train_test_split(cat_cols,test_size=0.2,random_state=42)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor','college']).reshape(1,2))

c:\Users\avanindra Bose\ML Tips\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[ 0., -1.]])

# Handling Infrequent Categories

In [27]:
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 +['snake'] * 3 + ['horse'] * 2], dtype=object).T
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

# Using Max Categories

-> It will only keep the max categories and rest all of them are consided as others

In [28]:
enc = OrdinalEncoder(max_categories=3).fit(X)

In [29]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [30]:
enc.transform(np.array([['cat','rabbit','snake','dog']]).reshape(4,1))

array([[0.],
       [1.],
       [2.],
       [2.]])

# Using Min frequency

-> It keeps min frequency category as the threshold.

In [31]:
enc = OrdinalEncoder(min_frequency=4).fit(X)
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [32]:
enc.transform(np.array([['cat','rabbit','snake','dog','horse']]).reshape(5,1))

array([[0.],
       [2.],
       [3.],
       [1.],
       [3.]])

# handling missing values

-> just like simple imputation technique. Anyways missing values should be handled first and then preprocessing steps must be applied.

In [33]:
# Example categorical data with missing values
data = [['Cat'], [np.nan], ['Dog'], ['Fish'], [np.nan]]

# Setting encoded_missing_value to -1, indicating we want missing values to be encoded as -1
encoder = OrdinalEncoder(encoded_missing_value=-1)

encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[ 0.]
 [-1.]
 [ 1.]
 [ 2.]
 [-1.]]
